apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: students.test-controller.io
spec:
  group: test-controller.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: students
    singular: student
    kind: Student
    shortNames:
    - stu
